spring:
  kafka:
    #为spark做流式计算的groupId
    spark-group-id: spark-consumer
    #为spark做流式计算的topic, 若有多个，以逗号分隔
    spark-topic: spark-streaming-kafka


    bootstrap-servers: 49.234.25.252:32797,49.234.25.252:32798
    producer:
      retries: 0
      #每次批量发送消息的数量
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
server:
  port: 8081

