spring:
  thymeleaf:
    prefix: classpath:/templates/
  #for single node
  redis:
    # Redis服务器地址 （默认为127.0.0.1）
    host: 127.0.0.1
    # Redis服务器连接端口 （默认为6379）
    port: 6379
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 2000ms
    jedis:
      pool:
        min-idle: 5
        max-idle: 10



